# TUGAS PRAKTIKUM
# SABTU, 21 SEPTEMBER 2024

## LIBRARY YANG DIBUTUHKAN

In [1]:
import pandas as pd

## MEMBACA DAN MENAMPILKAN DATASET

In [2]:
df = pd.read_csv('movie_sample_dataset.csv')

df

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,Color,Martin Scorsese,240,116866727.0,Biography|Comedy|Crime|Drama,The Wolf of Wall Street,2013,English,USA,100000000.0,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000
1,Color,Shane Black,195,408992272.0,Action|Adventure|Sci-Fi,Iron Man 3,2013,English,USA,200000000.0,7.2,"Robert Downey Jr.,Jon Favreau,Don Cheadle",95000
2,color,Quentin Tarantino,187,54116191.0,Crime|Drama|Mystery|Thriller|Western,The Hateful Eight,2015,English,USA,44000000.0,7.9,"Craig Stark,Jennifer Jason Leigh,Zoë Bell",114000
3,Color,Kenneth Lonergan,186,46495.0,Drama,Margaret,2011,English,usa,14000000.0,6.5,"Matt Damon,Kieran Culkin,John Gallagher Jr.",0
4,Color,Peter Jackson,186,258355354.0,Adventure|Fantasy,The Hobbit: The Desolation of Smaug,2013,English,USA,225000000.0,7.9,"Aidan Turner,Adam Brown,James Nesbitt",83000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Color,Steve McQueen,134,56667870.0,Biography|Drama|History,12 Years a Slave,2013,English,USA,20000000.0,8.1,"Quvenzhané Wallis,Scoot McNairy,Taran Killam",83000
95,Color,Richard J. Lewis,134,7501404.0,Comedy|Drama,Barney's Version,2010,English,Canada,NaN,7.3,"Mark Addy,Atom Egoyan,Paul Gross",0
96,Color,Paul Greengrass,134,107100855.0,Biography|Drama|Thriller,Captain Phillips,2013,English,USA,55000000.0,7.9,"Tom Hanks,Chris Mulkey,Michael Chernus",65000
97,Color,David Ayer,134,85707116.0,Action|Drama|War,Fury,2014,English,USA,68000000.0,7.6,"Brad Pitt,Logan Lerman,Jim Parrack",82000
98,Color,Clint Eastwood,5,47034272.0,Biography|Drama|Music|Musical,Jersey Boys,2014,English,USA,40000000.0,6.9,"Johnny Cannizzaro,Steve Schirripa,Scott Vance",16000

## MENGECEK TIPE DATA DAN MISSING VALUE

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   color                 88 non-null     object
 1   director_name         88 non-null     object
 2   duration              99 non-null     int64
 3   gross                 91 non-null     float64
 4   genres                98 non-null     object
 5   movie_title           99 non-null     object
 6   title_year            99 non-null     int64
 7   language              99 non-null     object
 8   country               99 non-null     object
 9   budget                95 non-null     float64
 10  imdb_score            99 non-null     float64
 11  actors                99 non-null     object
 12  movie_facebook_likes  99 non-null     int64
dtypes: float64(3), int64(3), object(7)
memory usage: 10.2+ KB

In [4]:
missing_values = df.isnull().sum()
print(missing_values)

color                   11
director_name           11
duration                 0
gross                    8
genres                   1
movie_title              0
title_year               0
language                 0
country                  0
budget                   4
imdb_score               0
actors                   0
movie_facebook_likes     0
dtype: int64

## CLEANING DATA

In [5]:
# df['color'] = df['color'].str.capitalize()
df.loc[:, 'color'] = df['color'].str.strip().str.capitalize()


df = df[(df['duration'] >= 0) & 
        (df['gross'] >= 0) & 
        (df['title_year'] >= 0) & 
        (df['budget'] >= 0) & 
        (df['imdb_score'] >= 0) & 
        (df['movie_facebook_likes'] >= 0)]

df = df.replace('N/A', pd.NA)

# df.dropna(subset=['duration', 'gross', 'title_year', 'budget', 'imdb_score', 'movie_facebook_likes'], inplace=True)
df.dropna(inplace=True)
df

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,Color,Martin Scorsese,240,116866727.0,Biography|Comedy|Crime|Drama,The Wolf of Wall Street,2013,English,USA,100000000.0,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000
1,Color,Shane Black,195,408992272.0,Action|Adventure|Sci-Fi,Iron Man 3,2013,English,USA,200000000.0,7.2,"Robert Downey Jr.,Jon Favreau,Don Cheadle",95000
2,Color,Quentin Tarantino,187,54116191.0,Crime|Drama|Mystery|Thriller|Western,The Hateful Eight,2015,English,USA,44000000.0,7.9,"Craig Stark,Jennifer Jason Leigh,Zoë Bell",114000
3,Color,Kenneth Lonergan,186,46495.0,Drama,Margaret,2011,English,usa,14000000.0,6.5,"Matt Damon,Kieran Culkin,John Gallagher Jr.",0
4,Color,Peter Jackson,186,258355354.0,Adventure|Fantasy,The Hobbit: The Desolation of Smaug,2013,English,USA,225000000.0,7.9,"Aidan Turner,Adam Brown,James Nesbitt",83000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,Color,Tony Gilroy,135,113165635.0,Action|Adventure|Thriller,The Bourne Legacy,2012,English,USA,125000000.0,6.7,"Jeremy Renner,Scott Glenn,Stacy Keach",31000
94,Color,Steve McQueen,134,56667870.0,Biography|Drama|History,12 Years a Slave,2013,English,USA,20000000.0,8.1,"Quvenzhané Wallis,Scoot McNairy,Taran Killam",83000
96,Color,Paul Greengrass,134,107100855.0,Biography|Drama|Thriller,Captain Phillips,2013,English,USA,55000000.0,7.9,"Tom Hanks,Chris Mulkey,Michael Chernus",65000
97,Color,David Ayer,134,85707116.0,Action|Drama|War,Fury,2014,English,USA,68000000.0,7.6,"Brad Pitt,Logan Lerman,Jim Parrack",82000
98,Color,Clint Eastwood,5,47034272.0,Biography|Drama|Music|Musical,Jersey Boys,2014,English,USA,40000000.0,6.9,"Johnny Cannizzaro,Steve Schirripa,Scott Vance",16000

In [6]:
missing_values = df.isnull().sum()
print(missing_values)

color                   0
director_name           0
duration                0
gross                   0
genres                  0
movie_title             0
title_year              0
language                0
country                 0
budget                  0
imdb_score              0
actors                  0
movie_facebook_likes    0
dtype: int64

## TRANSFORM DATA

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 67 entries, 0 to 98
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   color                 67 non-null     object
 1   director_name         67 non-null     object
 2   duration              67 non-null     int64
 3   gross                 67 non-null     float64
 4   genres                67 non-null     object
 5   movie_title           67 non-null     object
 6   title_year            67 non-null     int64
 7   language              67 non-null     object
 8   country               67 non-null     object
 9   budget                67 non-null     float64
 10  imdb_score            67 non-null     float64
 11  actors                67 non-null     object
 12  movie_facebook_likes  67 non-null     int64
dtypes: float64(3), int64(3), object(7)
memory usage: 7.3+ KB

In [8]:
df['budget'] = pd.to_numeric(df['budget'], errors='coerce')
df['gross'] = pd.to_numeric(df['gross'], errors='coerce')
print(df.dtypes)

color                    object
director_name            object
duration                  int64
gross                   float64
genres                   object
movie_title              object
title_year                int64
language                 object
country                  object
budget                  float64
imdb_score              float64
actors                   object
movie_facebook_likes      int64
dtype: object

In [9]:
df['actors'] = df['actors'].str.replace(',', ', ', regex=False)

df['genres'] = df['genres'].str.replace('|', ', ', regex=False)

df

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,Color,Martin Scorsese,240,116866727.0,"Biography, Comedy, Crime, Drama",The Wolf of Wall Street,2013,English,USA,100000000.0,8.2,"Leonardo DiCaprio, Matthew McConaughey, Jon Fa...",138000
1,Color,Shane Black,195,408992272.0,"Action, Adventure, Sci-Fi",Iron Man 3,2013,English,USA,200000000.0,7.2,"Robert Downey Jr., Jon Favreau, Don Cheadle",95000
2,Color,Quentin Tarantino,187,54116191.0,"Crime, Drama, Mystery, Thriller, Western",The Hateful Eight,2015,English,USA,44000000.0,7.9,"Craig Stark, Jennifer Jason Leigh, Zoë Bell",114000
3,Color,Kenneth Lonergan,186,46495.0,Drama,Margaret,2011,English,usa,14000000.0,6.5,"Matt Damon, Kieran Culkin, John Gallagher Jr.",0
4,Color,Peter Jackson,186,258355354.0,"Adventure, Fantasy",The Hobbit: The Desolation of Smaug,2013,English,USA,225000000.0,7.9,"Aidan Turner, Adam Brown, James Nesbitt",83000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,Color,Tony Gilroy,135,113165635.0,"Action, Adventure, Thriller",The Bourne Legacy,2012,English,USA,125000000.0,6.7,"Jeremy Renner, Scott Glenn, Stacy Keach",31000
94,Color,Steve McQueen,134,56667870.0,"Biography, Drama, History",12 Years a Slave,2013,English,USA,20000000.0,8.1,"Quvenzhané Wallis, Scoot McNairy, Taran Killam",83000
96,Color,Paul Greengrass,134,107100855.0,"Biography, Drama, Thriller",Captain Phillips,2013,English,USA,55000000.0,7.9,"Tom Hanks, Chris Mulkey, Michael Chernus",65000
97,Color,David Ayer,134,85707116.0,"Action, Drama, War",Fury,2014,English,USA,68000000.0,7.6,"Brad Pitt, Logan Lerman, Jim Parrack",82000
98,Color,Clint Eastwood,5,47034272.0,"Biography, Drama, Music, Musical",Jersey Boys,2014,English,USA,40000000.0,6.9,"Johnny Cannizzaro, Steve Schirripa, Scott Vance",16000

## FINAL DATASET

In [10]:
df.to_csv('movie_dataset_cleaned.csv', index=False)

df

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,Color,Martin Scorsese,240,116866727.0,"Biography, Comedy, Crime, Drama",The Wolf of Wall Street,2013,English,USA,100000000.0,8.2,"Leonardo DiCaprio, Matthew McConaughey, Jon Fa...",138000
1,Color,Shane Black,195,408992272.0,"Action, Adventure, Sci-Fi",Iron Man 3,2013,English,USA,200000000.0,7.2,"Robert Downey Jr., Jon Favreau, Don Cheadle",95000
2,Color,Quentin Tarantino,187,54116191.0,"Crime, Drama, Mystery, Thriller, Western",The Hateful Eight,2015,English,USA,44000000.0,7.9,"Craig Stark, Jennifer Jason Leigh, Zoë Bell",114000
3,Color,Kenneth Lonergan,186,46495.0,Drama,Margaret,2011,English,usa,14000000.0,6.5,"Matt Damon, Kieran Culkin, John Gallagher Jr.",0
4,Color,Peter Jackson,186,258355354.0,"Adventure, Fantasy",The Hobbit: The Desolation of Smaug,2013,English,USA,225000000.0,7.9,"Aidan Turner, Adam Brown, James Nesbitt",83000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,Color,Tony Gilroy,135,113165635.0,"Action, Adventure, Thriller",The Bourne Legacy,2012,English,USA,125000000.0,6.7,"Jeremy Renner, Scott Glenn, Stacy Keach",31000
94,Color,Steve McQueen,134,56667870.0,"Biography, Drama, History",12 Years a Slave,2013,English,USA,20000000.0,8.1,"Quvenzhané Wallis, Scoot McNairy, Taran Killam",83000
96,Color,Paul Greengrass,134,107100855.0,"Biography, Drama, Thriller",Captain Phillips,2013,English,USA,55000000.0,7.9,"Tom Hanks, Chris Mulkey, Michael Chernus",65000
97,Color,David Ayer,134,85707116.0,"Action, Drama, War",Fury,2014,English,USA,68000000.0,7.6,"Brad Pitt, Logan Lerman, Jim Parrack",82000
98,Color,Clint Eastwood,5,47034272.0,"Biography, Drama, Music, Musical",Jersey Boys,2014,English,USA,40000000.0,6.9,"Johnny Cannizzaro, Steve Schirripa, Scott Vance",16000